---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - core.infra.upcloud.com
  resources:
  - virtualmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.infra.upcloud.com
  resources:
  - virtualmachines/finalizers
  verbs:
  - update
- apiGroups:
  - core.infra.upcloud.com
  resources:
  - virtualmachines/status
  verbs:
  - get
  - patch
  - update
