# permissions for end users to edit virtualmachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: virtualmachine-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: uks-controller
    app.kubernetes.io/part-of: uks-controller
    app.kubernetes.io/managed-by: kustomize
  name: virtualmachine-editor-role
rules:
- apiGroups:
  - core.infra.upcloud.com
  resources:
  - virtualmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.infra.upcloud.com
  resources:
  - virtualmachines/status
  verbs:
  - get
