apiVersion: core.infra.upcloud.com/v1alpha1
kind: VirtualMachine
metadata:
  labels:
    app.kubernetes.io/name: virtualmachine
    app.kubernetes.io/instance: virtualmachine-sample
    app.kubernetes.io/part-of: uks-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: uks-controller
  name: virtualmachine-sample
spec:
  # TODO(user): Add fields here
